mikemayhemdev/DownfallSTS

src/main/java/downfall/patches/actlikeit/MapCompatiblity.java
src/main/java/downfall/patches/ui/map/FlipMap.java

fixes the ability to enter boss rooms
there's a lot of other stuff it does though, so custom acts probably still may have issues.
NOTE:
<dependency>
<groupId>actlikeit</groupId>
<artifactId>actlikeit</artifactId>
<version>1.0.0</version>
<scope>system</scope>
<systemPath>${workshopFolder}1934902042/actlikeit.jar</systemPath>
</dependency>
will be required in pom for compilation

actlikeit compatibility

---

src/main/java/charbosses/orbs/AbstractEnemyOrb.java

avoids replay patch within the AbstractOrb renderText method

replay orb patch compatibility

---

src/main/java/compatibility/replay/portal/FlipPortal.java

replay portal flip

---

src/main/java/expansioncontent/cards/HyperBeam.java

it's multi damage
reported in a comment - https://controlc.com/a7cf60ed

fix hyper beam

---

src/main/java/sneckomod/cards/PerplexingStare.java

not likely to happen since you need infinite journal or something, but someone reported it

prevent crash if upgraded too many times

---

src/main/java/downfall/patches/actlikeit/MapCompatiblity.java

for REAL should fix act like it compatibility issues attempting to fight the heart hopefully.

actlikeitcompatiblityagain

---

src/main/java/charbosses/actions/unique/EnemyBlockPerNonAttackAction.java
src/main/java/charbosses/actions/unique/EnemyExhaustNonAttacksAction.java
src/main/java/charbosses/bosses/Ironclad/CharBossIronclad.java
src/main/java/charbosses/bosses/Ironclad/NewAge/ArchetypeAct1StatusesNewAge.java
src/main/java/charbosses/cards/curses/EnIcky.java
src/main/java/charbosses/cards/red/EnBerserk.java
src/main/java/charbosses/cards/red/EnImmolate.java
src/main/java/charbosses/cards/red/EnPowerThrough.java
src/main/java/charbosses/cards/red/EnRecklessCharge.java
src/main/java/charbosses/cards/red/EnSeverSoul.java
src/main/java/charbosses/cards/red/EnThunderclap.java
src/main/java/charbosses/cards/status/EnBurn.java
src/main/java/charbosses/cards/status/EnDazed.java
src/main/java/charbosses/cards/status/EnSlimed.java
src/main/java/charbosses/powers/cardpowers/EnemyBerserkPower.java
src/main/java/charbosses/relics/CBR_ChampionsBelt.java
src/main/java/charbosses/relics/CBR_CharonsAshes.java
src/main/resources/downfallResources/localization/eng/MonsterStrings.json

Has not been tested yet, probably has some bugs.

Added Ironclad Act 1 Status Archetype

---

src/main/java/charbosses/bosses/Ironclad/NewAge/ArchetypeAct1StatusesNewAge.java
src/main/java/charbosses/cards/curses/EnHaunted.java
src/main/java/charbosses/cards/curses/EnIcky.java
src/main/java/charbosses/cards/red/EnBash.java
src/main/java/charbosses/cards/red/EnImmolate.java
src/main/java/charbosses/cards/red/EnRecklessCharge.java
src/main/java/charbosses/cards/red/EnThunderclap.java
src/main/java/charbosses/cards/red/EnWildStrike.java
src/main/java/charbosses/cards/status/EnBurn.java
src/main/java/charbosses/relics/CBR_ChampionsBelt.java

All right, I think I've done all I can do for this boss.
Couple bugs left, Champion's Belt & Icky don't work.

IC Act 1 Mostly Finished

---

src/main/java/charbosses/bosses/Defect/NewAge/ArchetypeAct3OrbsNewAge.java
src/main/java/charbosses/bosses/Silent/NewAge/ArchetypeAct2MirrorImageNewAge.java
src/main/java/charbosses/cards/blue/EnMulticast.java
src/main/java/charbosses/cards/blue/EnReinforcedBody.java
src/main/java/charbosses/monsters/MushroomPurple.java
src/main/java/charbosses/monsters/MushroomRed.java
src/main/java/charbosses/monsters/MushroomWhite.java
src/main/java/charbosses/powers/DefectCuriosityPower.java

Defect 3:
Removed Auto-shields and replaced with Reinforced Body
Added ability to change Multicast's cost (2 before loop, 3 in loop)
Fixed Superstorm activating on Defect's own powers
Ironclad 2:
Mushroom HP 20 -> 25
Doubled attack/block of red/white mushrooms respectively
Silent 2:
Gave Jax+ at base, Deflect+ on Ascension 4

Defect 3 Fixes & Silent 2 and Ironclad 2 Buffs

---

src/main/java/expansioncontent/cards/InvincibleStrength.java

To prevent playing it in the same turn as another boss card

Add STUDY tag to boss card Invincible

---

src/main/java/automaton/cards/Decompile.java

Code copied from Bit/Byte Shift

Fix Decompile (Dev Tools) not updating function preview

---

src/main/java/guardian/cards/ArmoredProtocol.java
src/main/java/theHexaghost/cards/StepThrough.java

also fix an oops in the last PR

Fix Armored Protocol wrongly applying Metallicize

---

src/main/java/theHexaghost/HexaMod.java
src/main/java/theHexaghost/events/WanderingSpecter.java
src/main/resources/hexamodResources/localization/eng/EventStrings.json

Also made it Act 1 exclusive.
Also fixed a small typo. Singing -> Singeing

Made Blue Candle optional in Wandering Specter event

---

src/main/java/downfall/patches/GlobalExtraCardUIPatch.java

Also fix card headers overlapping the energy symbol

Fix missing Unknown card headers on unplayables

---

src/main/java/automaton/cards/Explode.java
src/main/java/expansioncontent/cards/PrepareCrush.java
src/main/java/guardian/cards/AbstractGuardianCard.java
src/main/java/guardian/cards/ArmoredProtocol.java
src/main/java/guardian/cards/CurlUp.java
src/main/java/guardian/cards/EvasiveProtocol.java
src/main/java/guardian/cards/Gem_Lightblue.java
src/main/java/guardian/cards/GuardianWhirl.java
src/main/java/guardian/cards/Harden.java
src/main/java/guardian/cards/RevengeProtocol.java
src/main/java/guardian/cards/SpikerProtocol.java
src/main/java/guardian/powers/BracePerTurnPower.java
src/main/java/guardian/powers/ModeShiftPower.java
src/main/java/guardian/relics/ModeShifter.java
src/main/java/slimebound/cards/PrepareCrush.java
src/main/java/slimebound/cards/SlimeCrush.java
src/main/java/slimebound/powers/NextTurnGainSlimeCrush.java
src/main/resources/bronzeResources/localization/eng/CardStrings.json
src/main/resources/expansioncontentResources/localization/eng/CardStrings.json
src/main/resources/guardianResources/localization/eng/CardStrings.json
src/main/resources/guardianResources/localization/eng/PowerStrings.json
src/main/resources/guardianResources/localization/eng/RelicStrings.json
src/main/resources/slimeboundResources/localization/eng/CardStrings.json
src/main/resources/slimeboundResources/localization/eng/PowerStrings.json

Guardian Changes:
Bronze Gear, Curl Up, Armored/Evasive/Spiker/Revenge Protocol, Tourmaline
Also changed Explode (Automaton) and Prepare: Crush (Slime Boss & Boss Card)

Guardian Changes / Other Minor Feedback

---

src/main/resources/hexamodResources/localization/eng/UIStrings.json

Fixes an issue introduced in fbc99e4cb79b774b5b6d18d8a15baed9add4dd4b

Fix crash in rewards after using Sixth Seal

---

src/main/java/charbosses/relics/AbstractCharbossRelic.java
src/main/java/charbosses/relics/CBR_ArtOfWar.java
src/main/java/charbosses/relics/CBR_MercuryHourglass.java
src/main/java/charbosses/relics/CBR_OrnamentalFan.java

Fix Bosses' Lizard Tail not greying out, and other tweaks

---

src/main/java/guardian/actions/PolyBeamAction.java
src/main/java/guardian/cards/PolyBeam.java

Rewrites the card to be more similar to the current Sword Boomerang.
The previous version was based on old (and unused) boomerang code from
years ago.

Fix Poly Beam being completely blocked by a single Buffer stack

---

src/main/java/guardian/GuardianMod.java
src/main/java/guardian/actions/GemFireAction.java

https://user-images.githubusercontent.com/307683/113790389-f6a65700-96dc-11eb-9812-2c2c28781bc2.mp4

Gem Cannon vfx

---

src/main/java/expansioncontent/cards/DecaShield.java
src/main/java/expansioncontent/cards/PolyBeam.java

the previews weren't working but they are now

donu deca boss card preview fix

---

src/main/java/charbosses/cards/AbstractBossCard.java
src/main/java/charbosses/cards/red/EnReaper.java
src/main/java/downfall/downfallMod.java

Also fixes issues where buffs/debuffs on the minions didn't increase
Reaper's damage and healing

Fix player's Intangible reducing damage done to boss minions by Reaper

---

src/main/java/champ/powers/IronFortressVigorPower.java
src/main/java/downfall/patches/RelicOverrides.java
src/main/java/gremlin/potions/GremlinPotion.java
src/main/java/gremlin/potions/WizPotion.java
src/main/java/guardian/events/CrystalForge.java
src/main/java/slimebound/characters/SlimeboundCharacter.java
src/main/java/slimebound/patches/MaxOrbsPatch.java
src/main/java/slimebound/patches/OrbPositionPatch.java

Fix incorrect event text in Guardian's Crystal Forge event after canceling an option.
Fix incorrect art when clicking on the Courier to show details.
Fix incorrect orb positions for Slime Boss when fighting Shield and Spear.
Fix Slime Boss's maximum of 5 orb slots not being enforced.

Misc fixes

---

src/main/java/champ/cards/AbstractChampCard.java
src/main/java/champ/cards/IronFortress.java
src/main/java/champ/powers/IronFortressPower.java
src/main/java/champ/powers/IronFortressVigorPower.java
src/main/resources/champResources/localization/eng/PowerStrings.json

Changed the technical jig powers to so they call the given stance's technique a number of times equal to the stack of the power.

tech jig changes

---

src/main/java/champ/cards/AbstractChampCard.java
src/main/java/champ/cards/Encircle.java

Also changed the monsterList function in AbstractChampCard to a better check method.

Fixed Encircle to work when played via Distilled Chaos

---

src/main/java/downfall/VFXNotes
src/main/java/guardian/GuardianMod.java
src/main/java/guardian/actions/GemFireAction.java
src/main/java/guardian/actions/ReduceRightMostStasisAction.java
src/main/java/guardian/cards/BaubleBeam.java
src/main/java/guardian/cards/CrystalBeam.java
src/main/java/guardian/cards/PrismaticBeam.java
src/main/java/guardian/commands/SocketGems.java
src/main/java/guardian/vfx/CrystalRayEffect.java
src/main/java/slimebound/cards/FlameTackle.java

Flame Tackle
Bauble Burst
Prismatic Spray
Crystal Ray
Accelerate keyword
Plus a new console command for testing socketed cards

Various new VFX

---

src/main/java/downfall/patches/ui/map/FlipMap.java

Standard map generation forbids certain rooms from appearing twice in a
row, or twice as two paths coming from the same room. This change
ensures those rules still apply by reversing the "parents" associations
at the same time as the "edges".
Also removes an earlier attempt to fix the issue.

Fix doubled up rooms in downfall maps

---

src/main/java/gremlin/GremlinMod.java
src/main/java/gremlin/characters/GremlinCharacter.java
src/main/java/gremlin/patches/GremlinMobState.java

Also stops gremlin trenchcoat from appearing when you have no money

Fixing ascension damage

---

src/main/java/expansioncontent/cards/AbstractExpansionCard.java
src/main/java/expansioncontent/cards/DecaShield.java
src/main/java/expansioncontent/cards/PolyBeam.java
src/main/java/sneckomod/cards/AbstractSneckoCard.java

fixed an issue where exhuming donu blast before deca shield is created caused weird preview shenanigans

shapes boss card fix

---

src/main/java/theHexaghost/cards/AbstractHexaCard.java
src/main/java/theHexaghost/cards/BurningQuestion.java
src/main/java/theHexaghost/cards/GhostLash.java
src/main/java/theHexaghost/powers/GiftsFromTheDeadPower.java
src/main/java/theHexaghost/vfx/AfterlifePlayEffect.java

https://user-images.githubusercontent.com/307683/124014644-7d3a9f80-d97f-11eb-82b4-92e393816d24.mp4

New Afterlife VFX

---

pom.xml.example
src/main/java/downfall/downfallMod.java

quickrestart author claimed that this should be [fixed on downfall's end](https://steamcommunity.com/sharedfiles/filedetails/comments/1805046408), so here
am i doing this right

patch to work with quick restart

---

src/main/java/gremlin/patches/GremBtnPatch.java
src/main/java/sneckomod/patches/SnekBtnPatch.java

No guarantee without actual testing.

Attempting to fix missing gamemodes for Snecko and Gremlins

---

src/main/java/charbosses/bosses/Hermit/NewAge/ArchetypeAct1SharpshooterNewAge.java
src/main/java/charbosses/cards/hermit/EnDeadeye.java
src/main/java/charbosses/cards/hermit/EnDive.java
src/main/java/charbosses/cards/hermit/EnGhostlyPresence.java
src/main/java/charbosses/cards/hermit/EnHeadshot.java
src/main/java/charbosses/cards/hermit/EnRoughhouse.java
src/main/java/charbosses/cards/hermit/EnVirtue.java
src/main/java/charbosses/powers/bossmechanicpowers/HermitConcentrationPower.java
src/main/java/downfall/downfallMod.java
src/main/java/hermit/HermitMod.java
src/main/resources/downfallResources/localization/eng/PowerStrings.json
src/main/resources/downfallResources/localization/jpn/PowerStrings.json
src/main/resources/downfallResources/localization/kor/PowerStrings.json

Let's say that I tried to do something with Hermit 1, so it created small delay.

Bug Fixes + Hermit charboss cards update

---

src/main/java/champ/cards/Backstep.java
src/main/java/champ/cards/Circumvent.java
src/main/java/champ/cards/CrownThrow.java
src/main/java/champ/cards/GutPunch.java
src/main/java/champ/cards/PerfectedStrike.java
src/main/java/champ/cards/RageSigil.java
src/main/java/champ/cards/RapidStrikes.java
src/main/java/champ/cards/Shatter.java
src/main/java/champ/cards/ShieldThrow.java
src/main/java/champ/cards/SkillfulDodge.java
src/main/java/champ/cards/UltimateStance.java
src/main/java/theHexaghost/actions/ExhaustCardFromDiscardPile.java
src/main/java/theHexaghost/cards/Firestarter.java
src/main/java/theHexaghost/cards/FlamesFromBeyond.java
src/main/java/theHexaghost/cards/GhostLash.java
src/main/java/theHexaghost/cards/GhostOfSpireFuture.java
src/main/java/theHexaghost/cards/GhostOfSpirePresent.java
src/main/java/theHexaghost/cards/GhostShield.java
src/main/java/theHexaghost/cards/Sear.java
src/main/java/theHexaghost/patches/EndTurnAdvance.java
src/main/java/theHexaghost/powers/ApocalypticArmorPower.java
src/main/java/theHexaghost/powers/FuturePower.java
src/main/java/theHexaghost/powers/GainStrengthThatGoesAwayPower.java
src/main/java/theHexaghost/powers/PastPower.java
src/main/resources/champResources/localization/eng/CardStrings.json
src/main/resources/champResources/localization/zhs/CardStrings.json
src/main/resources/downfallResources/localization/eng/PowerStrings.json
src/main/resources/expansioncontentResources/localization/eng/KeywordStrings.json
src/main/resources/hexamodResources/localization/eng/CardStrings.json
src/main/resources/hexamodResources/localization/eng/PowerStrings.json

I don't even know where to begin, but there are still things to do.

Rework support

---

src/main/java/sneckomod/cards/unknowns/AbstractUnknownCard.java
src/main/java/sneckomod/patches/SingleCardViewPopupPatches.java

The preview cards will scroll automatically. The cards are also sorted by color, rarity, and name. The mousewheel may be used to scroll the cards. The automatic scrolling is paused for a few seconds after using the mousewheel.

Card preview for Snecko's Unknown cards now scrolls vertically

---

src/main/java/charbosses/bosses/Silent/NewAge/ArchetypeAct1PoisonNewAge.java
src/main/java/charbosses/cards/colorless/EnBlind.java
src/main/java/charbosses/cards/colorless/EnTrip.java
src/main/java/charbosses/cards/green/EnCripplingCloud.java
src/main/java/charbosses/cards/green/EnLegSweep.java
src/main/java/charbosses/cards/red/EnBash.java
src/main/java/charbosses/cards/red/EnClothesline.java
src/main/java/charbosses/cards/red/EnShockwave.java
src/main/java/charbosses/cards/red/EnUppercut.java
src/main/java/charbosses/powers/general/EnemyPoisonPower.java
src/main/java/downfall/monsters/gauntletbosses/Silent.java

Silent 1 A19 relic (Lantern) now actually does something
Fixed poison decreasing twice for Silent 1/Neow
Added Intangible to Wraith Form turn for Silent in Boss Gauntlet
Fixed issues with CharBoss weak/vuln cards not applying correct amounts

Polishing stuff

---

src/main/java/champ/ChampChar.java
src/main/java/guardian/cards/TwinSlam.java
src/main/java/guardian/powers/ModeShiftPower.java
src/main/java/hermit/relics/BartenderGlass.java
src/main/java/theHexaghost/cards/Floatwork.java
src/main/java/theHexaghost/cards/RadiantFlame.java
src/main/java/theHexaghost/cards/VolcanoVisage.java
src/main/java/theHexaghost/powers/RadiantPower.java
src/main/java/theHexaghost/powers/VolcanoVisagePower.java
src/main/resources/expansioncontentResources/localization/eng/PowerStrings.json
src/main/resources/guardianResources/localization/eng/CardStrings.json
src/main/resources/guardianResources/localization/kor/CardStrings.json
src/main/resources/guardianResources/localization/zhs/CardStrings.json
src/main/resources/hexamodResources/localization/eng/CardStrings.json
src/main/resources/hexamodResources/localization/eng/PowerStrings.json
src/main/resources/slimeboundResources/localization/eng/CardStrings.json

Radiant Flame reworked: now gives you Block whenever you Ignite a Ghostflame.
Volcano Visage reworked: now triggers whenever you Ignite a Ghostflame instead of doing it at start of the turn.
Also some descriptions were changed to be more consistent with base game.

Small Hexa changes + cleanup

---

src/main/java/charbosses/bosses/Watcher/NewAge/ArchetypeAct3DivinityNewAge.java
src/main/java/charbosses/cards/red/EnThunderclap.java
src/main/java/downfall/events/WingStatue_Evil.java
src/main/java/gremlin/patches/eventpatches/WingStatuePatch.java
src/main/java/guardian/relics/ModeShifter.java
src/main/resources/champResources/localization/eng/CardStrings.json
src/main/resources/champResources/localization/eng/PowerStrings.json
src/main/resources/downfallResources/localization/eng/EventStrings.json

Sharpened Fragment costs Max HP (half of prev damage cost)
Watcher 3 minor buffs (Empty Fist starts upgraded, Signature Move is the ascension upgrade)
Fixed issue with vanilla wing statue event text with Gremlins
Guardian starter relic refreshes at next floor
Minor Improvisation text change

Sharpened Fragment to Max HP, Watcher 3 buffs, other

---

src/main/java/charbosses/bosses/Silent/NewAge/ArchetypeAct1PoisonNewAge.java
src/main/java/charbosses/bosses/Silent/NewAge/ArchetypeAct3ShivsNewAge.java
src/main/java/charbosses/cards/green/EnBane.java
src/main/java/charbosses/powers/cardpowers/EnemyNoxiousFumesPower.java
src/main/java/charbosses/relics/CBR_MummifiedHand.java
src/main/java/theHexaghost/cards/HeatShield.java

The three commits were due to me messing up git stuff, whoops.
Patch Notes (not sure how much detail should be there, so I'm including everything):
Silent 1:
Adjusted incorrect damage value on Bane+
Noxious Fumes triggers at end of Silent's turn to avoid confusing interaction with Bane
Other balance adjustments
Silent 3:
Replaced Vajra with Mummified Hand
Replaced Infinite Blades with Piercing Wail

Silent 1 and 3 adjustments

---

src/main/java/expansioncontent/cards/ShapePower.java
src/main/resources/guardianResources/localization/eng/CardStrings.json
src/main/resources/guardianResources/localization/eng/KeywordStrings.json
src/main/resources/hexamodResources/localization/eng/CardStrings.json
src/main/resources/sneckomodResources/localization/eng/KeywordStrings.json
src/main/resources/sneckomodResources/localization/eng/UIStrings.json

Cutting Keywords.

---

src/main/java/champ/ChampChar.java
src/main/java/champ/cards/Execute.java
src/main/java/saveData/SaveData.java
src/main/java/sneckomod/OffclassHelper.java
src/main/java/sneckomod/SneckoMod.java
src/main/java/sneckomod/TheSnecko.java
src/main/java/sneckomod/actions/SerpentIdolAction.java
src/main/java/sneckomod/cards/ImprovisedAttack.java
src/main/java/sneckomod/cards/ImprovisedGuard.java
src/main/java/sneckomod/cards/IronFang.java
src/main/java/sneckomod/cards/SnekBite.java
src/main/java/sneckomod/cards/SoulDraw.java
src/main/java/sneckomod/cards/unknowns/AbstractUnknownCard.java
src/main/java/sneckomod/cards/unknowns/Unknown.java
src/main/java/sneckomod/powers/UnendingSupplyPower.java
src/main/java/sneckomod/relics/SneckoBoss.java
src/main/java/sneckomod/relics/SneckoCommon.java
src/main/resources/champResources/localization/eng/CardStrings.json
src/main/resources/guardianResources/localization/eng/CardStrings.json
src/main/resources/sneckomodResources/localization/eng/CardStrings.json

Moved few functions to Offclass Helper.
Balance:
Snecko HP reduced from 90 -> 85.
Snek Bite nerfed: damage reduced from 9 -> 7.
Snecko now starts with ??? Basic instead of ???.
Amount of classes chosen increased from 3 to 4.
Offclass card generation now respects class choices.
Iron Fang buffed: +1 to max damage/Block
Improvised cards +1 damage/Block.

Serpentine Choice part 3 of 77

---

src/main/resources/hexamodResources/localization/eng/CardStrings.json

Also reduced a number of keywords on cards.

Sorted Hexa's Cards JSON

---

src/main/java/sneckomod/SneckoMod.java
src/main/resources/sneckomodResources/localization/eng/CardStrings.json

So card view in card library not working was result of a typo.
Also sorted Snecko's card text JSON.

Fix to Pure Snecko.

---

src/main/java/sneckomod/OffclassHelper.java

Added a check if a card isn't from your class, as well as removed Healing cards from the pool.

Offclass generation fix.

---

src/main/java/sneckomod/SneckoMod.java
src/main/java/sneckomod/relics/SneckoBoss.java
src/main/java/sneckomod/relics/SneckoCommon.java

Snecko now has to think in 3D, as 4D was too much for some people.

Back to 3.

---

src/main/resources/hermitResources/localization/kor/CardStrings.json
src/main/resources/hermitResources/localization/kor/PowerStrings.json

I translated changed cards on 4.1.11.

kor localization

---

src/main/resources/bronzeResources/localization/fra/CardStrings.json
src/main/resources/champResources/localization/fra/CardStrings.json

Just a little patch for the status cards before the update :)

Petit boost

---

src/main/resources/hermitResources/localization/fra/CardStrings.json
src/main/resources/hermitResources/localization/fra/PowerStrings.json
src/main/resources/hermitResources/localization/fra/RelicStrings.json

Updated the cards in french for hermit

Boss Stuff (FR)

---

src/main/java/sneckomod/relics/SneckoCommon.java

Lucky Horseshoe is the SneckoBoss class

Fix wrong check in SneckoCommon

---

src/main/java/guardian/vfx/CrystalRayEffect.java

I've crashed twice to this, at least. I'm not sure how IDX is -1, but there's no point in letting it stay that way.

Small crash fix

---

src/main/resources/champResources/localization/kor/CardStrings.json
src/main/resources/reskinContent/localization/kor/UIStrings.json

[kor] small translation fix

---

src/main/java/guardian/cards/Preprogram.java
src/main/resources/hexamodResources/localization/zhs/CardStrings.json

used the same code for packmaster which seems to be causing rare crashes, so better be more catious with downfall.

crash prevent

---

src/main/resources/downfallResources/localization/fra/RelicStrings.json
src/main/resources/downfallResources/localization/fra/UIStrings.json
src/main/resources/guardianResources/localization/fra/CardStrings.json
src/main/resources/slimeboundResources/localization/fra/CardStrings.json

Saw there were some problems after the update, so I fixed them
All of the specific details are in the commits

Patch after update 

---

src/main/java/downfall/events/WingStatue_Evil.java
src/main/java/sneckomod/relics/BlankCard.java
src/main/java/theHexaghost/cards/UnlimitedPower.java

Blank Card nerfed: rarity changed from common to uncommon.
Unlimited Power buffed: Cost reduced by 1.
Sharpened Fragment : you need to lose slightly more hp to gain it in the Wing Statue event.

hot tweaks

---

src/main/java/collector/CollectorMod.java

This fixes invisible slots taking over the top panel

Make Collector's TopPaneltems Dynamically add and remove.
