src/main/java/downfall/patches/ShopRoomReplacePatch.java, src/main/java/downfall/patches/rooms/ShopRoomReplacePatch.java, src/main/java/downfall/patches/ui/map/FlipMap.java
This fixes the following bugs:
Consecutive shops on the map
- Fixes wrong replaceshop patches by replacing them with less incompatible insert patches
- Adding a manual check at the end just to be extra sure
Emerald elites in act 3 without campfire
- Manually checks map after creation and if no connected campfire is found, it changes the leftmost node connected to the elite to be a campfire
Elites and campfires spawning far too early:
- removes wrong if clause that prevented downfall map spawning rules from applying when normalmapLayout was false
=> Map creation bug fix bonanza

src/main/java/charbosses/bosses/AbstractCharBoss.java
This outer "damageAmount > 0" is meant to skip most of the logic
when an attack is fully blocked. Judgement sets the boss HP to zero and
then does a zero damage hit, skipping the logic. So, also run the logic
if the boss HP is zero.
=> Fix charbosses not dying to Judgement

src/main/java/guardian/relics/ModeShifterPlus.java, src/main/java/slimebound/cards/DuplicatedForm.java, src/main/resources/champResources/localization/eng/PowerStrings.json
fixed strike of genius's power text still referring to stances rather than strikes
fixed guardian gear (upgraded guardian starter relic) giving you 8 block instead of 10 block
fixed **un**upgraded duplicated form giving you +1 energy per turn.
=> misc fixes

src/main/resources/champResources/localization/eng/UIStrings.json
Seems like the prompt automatically starts with "Choose a card to", so all three of the Enchant cards needed that part of their string removed. "Choose a card to Choose a card to cost 0." was what we were seeing.
=> champ's "enchant" cards prompt fix

src/main/java/theHexaghost/cards/StepThrough.java
Without the ghostwheel effect, it's worse than a Strike. Forked Flame is also banned and does 1 more damage.
=> Ban Step Through from Unknown cards

src/main/java/slimebound/orbs/SlowingSlime.java
Fixing null pointer exception for when vfx cleanup happens before postSpawnEffects
=> Fixing null pointer exception in SlowingSlime

src/main/java/champ/ChampMod.java, src/main/java/downfall/patches/BanSharedContentPatch.java, src/main/java/sneckomod/SneckoMod.java, src/main/java/theHexaghost/HexaMod.java
Run locks shared potions for Snecko, Hexaghost, and Champ, so unique mechanics don't appear before the characters are played
=> Run locking potions for champ, snecko, and hexaghost

src/main/java/guardian/patches/SelfStasisPatch.java
Fixes an issue where playing Duplication Pot followed by Charge Core results in this glitched stasis slot. Probably fixes the same issue with Necronomicon, Double Tap and similar.
=> Fix Dupe Pot putting glitched copies of self-stasis cards in stasis

src/main/java/sneckomod/util/ColorfulCardReward.java
Rewards no longer give SPECIAL rarity cards (cards generated in combat
and event rewards) and BANNEDFORSNECKO cards (ghostwheel cards and gems,
mostly).
=> Fix Lucky Horseshoe giving unsuitable card rewards

src/main/java/sneckomod/patches/SnekCardPoolPatch.java, src/main/java/sneckomod/relics/SneckoBoss.java, src/main/java/sneckomod/relics/SneckoCommon.java
Fix an issue where other char cards appear after changing acts or saving.
Fix an issue where Seal completely forgets the chosen char after exiting.
Ensure that Seal and Horseshoe always use the same char regardless of
pickup order.
=> Fix various issues with Seal of Approval and Lucky Horseshoe

src/main/java/sneckomod/relics/BlankCard.java
For instance, Gremlin Dance crashing because it doesn't know which
gremlin is in front until applyPowers is called.
=> Fix various crashes caused by Blank Card

src/main/java/gremlin/GremlinMod.java
Prevents words like "swap" from triggering incorrect keywords
=> Add gremlin mod ID to its keywords

src/main/java/charbosses/bosses/AbstractCharBoss.java, src/main/java/charbosses/bosses/Ironclad/NewAge/ArchetypeAct3BlockNewAge.java, src/main/java/charbosses/bosses/Watcher/NewAge/ArchetypeAct2CalmNewAge.java, src/main/java/charbosses/cards/AbstractBossCard.java, src/main/java/charbosses/monsters/Fortification.java, src/main/java/charbosses/powers/bossmechanicpowers/FakeOrRealPower.java, src/main/java/charbosses/powers/bossmechanicpowers/IroncladFortificationPower.java, src/main/java/charbosses/relics/CBR_IncenseBurner.java, src/main/resources/downfallResources/localization/eng/PowerStrings.json, src/main/resources/downfallResources/localization/zhs/PowerStrings.json
Fixed Act 3 Ironclad's Body Slam sometimes having an incorrect intent
Fixed Act 2 Watcher's Flying Sleeves having an incorrect intent
Act 2 Watcher's Incense Burner pulsates whenever she is intangible
Fix Act 2 Silent's mirror image incorrectly taking hits from random-enemy attacks (Sword Boomerang, etc) after it is killed
=> Fix several incorrect intents on boss cards, and other improvements

src/main/java/sneckomod/relics/BlankCard.java
The crash occurs when the Gremlin starter relic swaps to the Mad
gremlin after the card is already in queue. Since the card in queue is
expecting to find a different gremlin in front, it crashes on Mad's
multi-damage attack because the multiDamage field is null. This isn't
obvious because the stack trace has incorrect line numbers within code
patched by basemod.
The fix of calling applyPowers was inspired by the code of the vanilla
card Havoc.
Rather than trying to find a different fix inside Gremlin Dance, this
fix ensures Blank Card will call applyPowers just before playing the
card, which hopefully avoids similar corner case crashes with
start-of-battle relics and other cards.
=> Fix rare crash with Blank Card, Gremlin Dance, and starter relic

src/main/java/automaton/powers/HardenedFormPower.java, src/main/java/champ/cards/SteelEdge.java, src/main/java/expansioncontent/cards/DecaShield.java, src/main/java/expansioncontent/cards/PolyBeam.java, src/main/java/expansioncontent/powers/PretendHexWheelPower.java, src/main/java/gremlin/actions/PseudoDamageRandomEnemyAction.java, src/main/java/guardian/actions/PolyBeamAction.java, src/main/java/guardian/cards/GatlingBeam.java, src/main/java/guardian/relics/PocketSentry.java, src/main/java/sneckomod/actions/BabySneckoAttackAction.java, src/main/java/theHexaghost/actions/EmbersAction.java, src/main/java/theHexaghost/cards/Incineration.java, src/main/resources/champResources/localization/eng/RelicStrings.json
fixed Steel Edge giving wrong "can't play" message
fixed donu/deca boss card crashing when upgraded during combat
fixed berserker's guide having an outdated and completely inaccurate description
fixed fragmentation grenade not working on a number of sources of random damage.
=> steel edge, donu/deca card crash, berserker's guide, frag grenade

src/main/java/downfall/events/CursedFountain.java, src/main/java/theHexaghost/actions/ChargeCurrentFlameAction.java, src/main/java/theHexaghost/actions/RecurringNightmareAction.java, src/main/java/theHexaghost/cards/BurningQuestion.java, src/main/java/theHexaghost/cards/StrikeFromBeyond.java, src/main/java/theHexaghost/ghostflames/AbstractGhostflame.java, src/main/resources/downfallResources/localization/eng/EventStrings.json, src/main/resources/hexamodResources/localization/eng/CardStrings.json, src/main/resources/sneckomodResources/localization/eng/KeywordStrings.json
Fixed Burning Question+ being upgradeable multiple times
Fixed Cursed Fountain event having mixed up strings (ENG localization only since I can't speak chinese)
Fixed Strike from Beyond not being a Strike card
Fixed Nightmare Vision+'s exhume action being weird
Slightly improved the Offclass keyword to clarify that statuses and curses are offclass.
Fixed Instant Inferno+ to force-ignite the active ghostflame correctly.
=> Burning Question, Strike from Beyond, Nightmare Vision, and text fixes

src/main/java/guardian/powers/ModeShiftPower.java
Remove an old check that was added back when C.Form prevented HP
instead of adding Strength.
=> Fix Construction Form breaking Mode Shifter for the rest of the fight

src/main/java/downfall/patches/ui/map/FlipMap.java
Issue was that elites are prevented from spawning in the upper floors of
the map, so the map must be populated in reverse order to allow
those elites to spawn again in the lower floors.
=> Fix missing elites in downfall maps

src/main/java/gremlin/characters/GremlinCharacter.java, src/main/java/gremlin/patches/CampfireRestPatch.java, src/main/java/gremlin/patches/GremlinPostBossHealPatch.java, src/main/java/gremlin/patches/eventpatches/GhostsPatch.java, src/main/java/gremlin/patches/eventpatches/VampiresPatch.java
Nerfing post boss and campfire resurrections.
Fixing the percentage max hp loss events (vampires/ghosts)
=> Gremlin Rez/HP nerfs

src/main/java/saveData/SaveData.java, src/main/java/saveData/downfallSaveData.java, src/main/java/sneckomod/SneckoMod.java, src/main/java/sneckomod/patches/GenerateSeedsPatch.java, src/main/java/sneckomod/relics/SuperSneckoEye.java, src/main/java/sneckomod/ui/LockInCampfireEffect.java, src/main/java/sneckomod/ui/LockInCampfireOption.java
Cards shown by Identify will be the same at subsequent campfires until
a card is identified. Identify uses a new, distinct RNG to ensure no
other actions will affect the cards shown, with the exception that
removing an unknown might reroll any that were acquired more recently.
Memorize will not affect the Identify RNG.
=> Snecko's Identify is now seeded and can be canceled

src/main/java/automaton/cards/RecursiveStrike.java, src/main/java/theHexaghost/actions/EmbersAction.java, src/main/java/theHexaghost/cards/RainOfEmbers.java, src/main/java/theHexaghost/patches/NoMoreUpgradePopup.java, src/main/resources/champResources/localization/eng/CardStrings.json, src/main/resources/hexamodResources/localization/eng/CardStrings.json
Recursive Strike now has a Strike Tag.
Rain of Embers secondary effect works with Chemical X.
Seals now have a visible upgrade button in card library.
Fixed to a typo in Technical Jig's description.
Changed the descriptions of Finish Him and Burning Touch to be less confusing.
Rest of this is just a tangent.
This description is worded that way to suggest that Hp check happens before dealing damage, so every fight does not require math similar to Slimeboss fight, so please do not change it unless the card is reworked. Also I am keeping the percent as something that can be changed in the card, because I feel that it would be required to balance the card later.
=> Minor fixes.

src/main/java/guardian/cards/AbstractGuardianCard.java, src/main/java/guardian/cards/GatlingBeam.java, src/main/java/guardian/orbs/StasisOrb.java, src/main/resources/guardianResources/localization/eng/CardStrings.json
Remains in stasis for !M! turns regardless of how it got there. Comes out of stasis with 0 cost like any other card in stasis.
=> Laser Turret rework: immediate damage and long stasis

src/main/java/theHexaghost/actions/SacrificeAction2.java
Was crashing when only one card was in hand because there were two if statements covering that case. I just deleted one, seems to be working fine now.
=> Worthy Sacrifice Bug Fix

src/main/java/charbosses/bosses/HighlightCards.java, src/main/java/charbosses/powers/bossmechanicpowers/SilentShivTimeEaterPower.java, src/main/java/expansioncontent/cards/DashGenerateEvil.java, src/main/java/gremlin/cards/GremlinArms.java, src/main/java/gremlin/cards/SupplyScrollCard.java, src/main/resources/downfallResources/localization/eng/CardStrings.json, src/main/resources/expansioncontentResources/localization/eng/CardStrings.json, src/main/resources/expansioncontentResources/localization/jpn/CardStrings.json, src/main/resources/expansioncontentResources/localization/kor/CardStrings.json, src/main/resources/expansioncontentResources/localization/zhs/CardStrings.json, src/main/resources/gremlinResources/localization/eng/CardStrings.json, src/main/resources/gremlinResources/localization/eng/KeywordStrings.json, src/main/resources/gremlinResources/localization/jpn/CardStrings.json, src/main/resources/gremlinResources/localization/jpn/KeywordStrings.json
Patch Notes:
The Evil Within now applies block before dealing damage, similar to Dash.
Gremlins' Steal effect is now a keyword.
Highlighting in Silent 3 fight fixed for cards that temporarily cost 0.
Other minor gameplay / text fixes.
=> Lots of small changes

src/main/java/charbosses/actions/vfx/cardmanip/EnemyShowCardAndAddToHandEffect.java, src/main/java/charbosses/cards/AbstractBossCard.java, src/main/java/charbosses/cards/blue/EnFusion.java, src/main/java/charbosses/cards/blue/EnReinforcedBody.java, src/main/java/charbosses/cards/green/EnPhantasmalKiller.java, src/main/java/charbosses/cards/green/EnSkewer.java, src/main/java/charbosses/cards/purple/EnCarveReality.java, src/main/java/charbosses/cards/purple/EnLessonLearned.java, src/main/java/charbosses/cards/purple/EnMasterReality.java, src/main/java/charbosses/cards/purple/EnMeditate.java, src/main/java/charbosses/cards/red/EnSpotWeakness.java, src/main/java/charbosses/cards/red/EnSwordBoomerang.java, src/main/java/charbosses/orbs/AbstractEnemyOrb.java, src/main/java/charbosses/orbs/EnemyPlasma.java, src/main/java/charbosses/powers/cardpowers/EnemyDevaFormPower.java, src/main/java/charbosses/powers/cardpowers/EnemyMasterRealityPower.java, src/main/java/charbosses/powers/cardpowers/EnemyPhantasmalPower.java, src/main/java/charbosses/powers/cardpowers/EnemySpotWeaknessPower.java, src/main/java/charbosses/powers/cardpowers/EnemyVigorPower.java, src/main/java/charbosses/relics/CBR_Duality.java, src/main/java/charbosses/relics/CBR_Inserter.java, src/main/java/charbosses/relics/CBR_RunicCapacitor.java, src/main/java/charbosses/relics/CBR_Sozu.java, src/main/resources/downfallResources/localization/eng/PowerStrings.json
Relics added:
Duality
Runic Capacitor
Sozu
Relics fixed:
Inserter (now copying the right thing)
Akabeko (no longer triggers on attacks vs boss)
Cards added:
Fusion
Phantasmal Killer
Skewer
Lesson Learned
Master Reality
Meditate
Spot Weakness
Cards fixed:
Reinforced body (now actually Defend and uses right energy)
Tranquility (no longer suggested it blocks)
Sword boomerang (now actually does multidamage for intent purposes)
Deva form (now states correct energy gain on mouseover)
Carve reality (now gives correct damage with master reality, appears in sensible place in hand and gives full damage in intent)
Fusion (plasma now triggers at end of boss turn (letting player see actual boss energy) and is no longer affected by focus)
=> Implementing cards and relics and fixing issues spotted

src/main/resources/guardianResources/localization/eng/CardStrings.json
Change Preprogram text to indicate that placing a card into stasis is mandatory, not optional.
=> Minor card text fix: Preprogram

src/main/java/charbosses/bosses/Hermit/NewAge/ArchetypeAct2WheelOfFateNewAge.java, src/main/java/hermit/actions/LoneWolfAction.java, src/main/java/hermit/actions/ReduceDebuffsAction.java, src/main/java/hermit/cards/Dissolve.java, src/main/java/hermit/cards/FinalCanter.java, src/main/java/hermit/cards/Virtue.java, src/main/java/hermit/powers/Rugged.java, src/main/resources/downfallResources/localization/eng/PowerStrings.json, src/main/resources/hermitResources/localization/eng/CardStrings.json
- Act 2 Hermit boss power reworded, gains Strength when drawing Necronomicurse again.
- Dissolve gains more Block.
- Final Canter no longer exhausts Curses. (That's Spite's job now.)
- Lone Wolf cost reduction no longer carries over turns if the card remains in your hand.
- Buffer now triggers before Rugged and thus protects it.
- Fixed Virtue and ReduceDebuffsAction as a whole.
=> More changes to Hermit

src/main/java/guardian/actions/BraceAction.java
This bug was reported by someone playing Spire Biomes because there are various ways to get cards from other characters. Bracing when the player didn't have `ModeShiftPower` would softlock because `BraceAction` queued an action that never set `isDone`.
This PR implements a fix, which is very simple. I tested it locally.
=> Guardian: fix Brace causing a softlock when the player doesn't have Mode Shift
